# Site settings
title: Ben McDowell
email: benmcdowelluk@gmail.com
description: >-
  Personal website of Ben McDowell, Computer Science and AI Student at the University of Bath.
baseurl: "" # For user or organization sites, leave this empty
url: "https://bmcd243.github.io" # Replace with your GitHub Pages URL
author: Ben McDowell

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults for various content
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      blog_active: true

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Jekyll 3 settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Jekyll 4 settings
include:
  - _pages

exclude:
  - README.md
  - templates/
  - config.json
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

# Social links
social:
  github: https://github.com/bmcd243
  linkedin: https://www.linkedin.com/in/ben-mcd

# Navigation
navigation:
  - name: home
    url: /
  - name: blog
    url: /blog/
  - name: cv
    url: /cv/
  - name: research
    url: /research/ 